name: Cypress API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Baixar binário do Cypress
        run: npx cypress install

      - name: Rodar testes de API com Cypress
        run: npx cypress run --spec "cypress/e2e/**/*.cy.js"

      - name: Gerar relatório Mochawesome
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/merged-report.json
          npx marge cypress/reports/merged-report.json -f report --reportDir cypress/reports/html

      - name: Copiar log de API para reports
        if: success() || failure()
        run: |
          mkdir -p cypress/reports/logs
          cp cypress/logs/api-log.json cypress/reports/logs/api-log.json || echo "Log não encontrado"

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Definir timestamp
        id: vars
        run: echo "timestamp=$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_OUTPUT

      - name: Renomear screenshots com timestamp
        if: success() || failure()
        run: |
          mkdir -p renamed_screenshots
          for file in cypress/screenshots//.png; do
            base=$(basename "$file")
            cp "$file" "renamed_screenshots/${{ steps.vars.outputs.timestamp }}_$base"
          done || echo "Nenhuma screenshot encontrada"

      - name: Enviar screenshots ao S3
        if: success() || failure()
        run: |
          aws s3 cp renamed_screenshots s3://cypress-api-qalabs/screenshots/ --recursive || echo "Nenhum arquivo para enviar"

      - name: Enviar relatórios e logs ao S3
        if: success() || failure()
        run: |
          aws s3 cp cypress/reports/html s3://cypress-api-qalabs/relatorios/ --recursive
          aws s3 cp cypress/reports/logs s3://cypress-api-qalabs/logs/ --recursive